// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "rcrawlback_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// r_crawlback_new
XPtr<CrawlbackWrapper> r_crawlback_new();
RcppExport SEXP rcrawlback_r_crawlback_new() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(r_crawlback_new());
    return __result;
END_RCPP
}
// r_crawlback_run
void r_crawlback_run(XPtr<CrawlbackWrapper> c, Function& onStart, Function& onRun, Function& onEnd);
RcppExport SEXP rcrawlback_r_crawlback_run(SEXP cSEXP, SEXP onStartSEXP, SEXP onRunSEXP, SEXP onEndSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<CrawlbackWrapper> >::type c(cSEXP);
    Rcpp::traits::input_parameter< Function& >::type onStart(onStartSEXP);
    Rcpp::traits::input_parameter< Function& >::type onRun(onRunSEXP);
    Rcpp::traits::input_parameter< Function& >::type onEnd(onEndSEXP);
    r_crawlback_run(c, onStart, onRun, onEnd);
    return R_NilValue;
END_RCPP
}
