// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "rcrawlback_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// r_crawlback_new
XPtr<CrawlbackWrapper> r_crawlback_new();
RcppExport SEXP rcrawlback_r_crawlback_new() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(r_crawlback_new());
    return __result;
END_RCPP
}
// r_crawlback_add_start_callback
void r_crawlback_add_start_callback(XPtr<CrawlbackWrapper> c, Function f);
RcppExport SEXP rcrawlback_r_crawlback_add_start_callback(SEXP cSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<CrawlbackWrapper> >::type c(cSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    r_crawlback_add_start_callback(c, f);
    return R_NilValue;
END_RCPP
}
// r_crawlback_run
void r_crawlback_run(XPtr<CrawlbackWrapper> c);
RcppExport SEXP rcrawlback_r_crawlback_run(SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<CrawlbackWrapper> >::type c(cSEXP);
    r_crawlback_run(c);
    return R_NilValue;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP rcrawlback_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello());
    return __result;
END_RCPP
}
