# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_crawlback_new <- function() {
    .Call('rcrawlback_r_crawlback_new', PACKAGE = 'rcrawlback')
}

r_crawlback_run <- function(c, onStart, onRun, onEnd) {
    invisible(.Call('rcrawlback_r_crawlback_run', PACKAGE = 'rcrawlback', c, onStart, onRun, onEnd))
}

