# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_crawlback_new <- function() {
    .Call('rcrawlback_r_crawlback_new', PACKAGE = 'rcrawlback')
}

r_crawlback_add_start_callback <- function(c, f) {
    invisible(.Call('rcrawlback_r_crawlback_add_start_callback', PACKAGE = 'rcrawlback', c, f))
}

r_crawlback_run <- function(c) {
    invisible(.Call('rcrawlback_r_crawlback_run', PACKAGE = 'rcrawlback', c))
}

rcpp_hello <- function() {
    .Call('rcrawlback_rcpp_hello', PACKAGE = 'rcrawlback')
}

